version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/movie_booking?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - JWT_SECRET=c2VjcmV0LWtleS13aXRoLWVub3VnaC1iaXQtbGVuZ3RoLXByb3RlY3Rpb24=
      - MAIL_USERNAME=your-email@gmail.com
      - MAIL_PASSWORD=your-app-password
      - CLOUD_NAME=your_cloud_name
      - API_KEY=your_api_key
      - API_SECRET=your_api_secret
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movie_booking
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: