spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/movie_booking}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET:0D4MZtm70C8HVYCVCBvGwat7LYec66C2I87Y+YyBZHg=}
  expiration: 3600000
cloudinary:
  cloud_name: ${CLOUD_NAME:dul9q7k8g}
  api_key: ${API_KEY:372722121212222}
  api_secret: ${API_SECRET:372722121212222}


