spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/movie_booking?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your-db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    docExpansion: list

jwt:
  secret: ${JWT_SECRET:your-base64-encoded-secret-key-that-is-very-long}
  expiration: 86400000
cloudinary:
  cloud_name: ${CLOUD_NAME:your-cloud-name}
  api_key: ${API_KEY:your-api-key}
  api_secret: ${API_SECRET:your-api-secret}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.backend.movie_ticket_booking_system: DEBUG
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: movie-ticket-booking
        version: ${project.version:0.0.1-SNAPSHOT}
        environment: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080
  error:
    include-message: always # helpful in dev
    include-binding-errors: always
    include-stacktrace: on_param # never in prod
    include-exception: false
